
services: 
  db:
    image: 'postgres:16.2-alpine'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:5432
    volumes: 
      - ./_database:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge